### ISSUE TITLE
Detailed instruction for installing "async.future"

### ISSUE THREAD

**Issue by Karry** [markussammallahti/harbour-slackfish#13]
Hi. 

I found that you are using async.future library (`asyncfuture.h`), can you provide detailed instruction how to install it for Sailfish/Mer SDK ? Your readme contains just note about qpm (Qt package manager), but I am not familiar with it and it is not available in SDK.

**Comment by markussammallahti** [comment]
Readme has link to http://www.qpm.io website that has download link to qpm executable.

When you run `qpm install` in project folder, it downloads packaged source code and adds it to the project, there is no need to do anything for the SDK itself.
