### ISSUE TITLE
Сhange sorting in main window to group channels and directs together

### ISSUE THREAD

**Issue by samfrown** [markussammallahti/harbour-slackfish#8]
Hello

Is it possible to change sorting in main window to group channels and directs together? 
Now all sorted in alphabetical order so direct contacts and groups are mixed up.

Thanks for app. It's great and helpful.

**Comment by DylanVanAssche** [comment]
I have the same 'problem' +1

**Comment by markussammallahti** [comment]
Slack dropped some fields from api responses that are used for sorting. I have fix ready and will be releases soon.

**Comment by DylanVanAssche** [comment]
Thanks!

**Comment by markussammallahti** [comment]
Fixed in 24812eacaaec365ef10f12635f972908c95f10c5 and will be included in next release
